### ISSUE TITLE
PTA

### ISSUE THREAD

**Issue by avgstuBoboge** [lifeInZUCC/ZUCC-intersection#1]
题解可以参考洛谷 www.luogu.com.cn
因为思路不同可能存在多种题解，然后增加点赞功能并按点赞数sort

**Comment by nonlinearthink** [comment]
> 题解可以参考洛谷 www.luogu.com.cn
> 
> 因为思路不同可能存在多种题解，然后增加点赞功能并按点赞数sort

因为我们使用的框架为文档型，并不是通用的web框架，我们很难做到这样的需求。
